
"""
Effect of dropout on MFA accuracy
"""

reps = list(range(1,51))
lls = ["0.02", "0.05", "0.1", "1", "10", "Inf"]

output_files = expand("data/dropout_test_{ll}_{rep}.csv",ll = lls, rep = reps)

rule all:
    input:
        "res.Rdata"

rule rmarkdown:
    output:
        "res.Rdata"
    shell:
        "Rscript -e \"rmarkdown::render('mix-sig-analysis.Rmd')\""
