
"""
Effect of dropout on MFA accuracy
"""

reps = list(range(1,21))
lls = ["0.5", "1", "10", "Inf"]

output_files = expand("data/dropout_test_{ll}_{rep}.csv",ll = lls, rep = reps)

rule all:
    input:
        output_files


rule quantify_dropout:
    output:
        "data/dropout_test_{ll}_{rep}.csv"
    shell:
        "Rscript --vanilla mfa_dropout_test.R {wildcards.ll} {wildcards.rep}"
